runtime: nodejs
env: flex
env_variables:
    REDISHOST: '10.10.58.219'
    REDISPORT: '6379'
network:
    name: default
manual_scaling:
  instances: 1
resources:
 cpu: 1
 memory_gb: 1
 disk_size_gb: 10

